@startuml

' style
skinparam Handwritten true
skinparam monochrome true

' class definitions
class Queue {
  -length: 8
  -queue: Char[length]
  -head: Int
  -tail: Int
  -size: Int
  +isFull(): Boolean
  +put(element: Char)
  +get(): Char
}

@enduml