@startuml

' style
skinparam Handwritten true
skinparam monochrome true

' class definitions
class Stack {
  -stack: String[100]
  -index: Int
  +isFull(): Boolean
  +push(element: String)
  +pop(): String
}

@enduml